import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database with all PSRS inventory and products...');
  await prisma.productLocation.deleteMany({});

  // 1. Seed Categories
  const categories = [
    { name: 'Drilling Rigs & Machinery' },
    { name: 'Rotation Motors' },
    { name: 'Crankcase' },
    { name: 'Piston Assembly' },
    { name: 'Valves' },
    { name: 'Bearings & Seals' },
    { name: 'Fasteners' },
    { name: 'Air System' },
  ];

  const categoryMap: Record<string, string> = {};

  for (const cat of categories) {
    const createdCat = await prisma.category.upsert({
      where: { name: cat.name },
      update: {},
      create: { name: cat.name },
    });
    categoryMap[cat.name] = createdCat.id;
  }
  console.log('Categories seeded:', Object.keys(categoryMap).length);

  // 2. Seed Warehouses
  const warehouses = [
    { name: 'Main Warehouse A', code: 'WH-A', address: 'Sanath Nagar Industrial Area, Hyderabad', capacity: 5000 },
    { name: 'Small Parts Sump B', code: 'WH-B', address: 'Peenya Industrial Area, Bengaluru', capacity: 3000 },
    { name: 'Bearing Drawer C', code: 'WH-C', address: 'Bhosari Industrial Area, Pune', capacity: 4000 },
    { name: 'Logistics Locker D', code: 'WH-D', address: 'Adyar Industrial Estate, Chennai', capacity: 2000 },
  ];

  const warehouseMap: Record<string, string> = {};
  for (const wh of warehouses) {
    const createdWh = await prisma.warehouse.upsert({
      where: { code: wh.code },
      update: {},
      create: wh,
    });
    warehouseMap[wh.name] = createdWh.id;
  }
  console.log('Warehouses seeded:', Object.keys(warehouseMap).length);

  // 3. Complete list of all Products to seed (including inventory spare parts and base rigs)
  const productsToSeed = [
    // Base Products (Rigs and Motors)
    {
      name: 'PSR-C300 Heavy Hydraulic Crawler Drill',
      sku: 'PSR-C300-CRAWLER',
      code: 'PSR-C300',
      category: 'Drilling Rigs & Machinery',
      subCategory: 'Crawler Drills',
      compatibleMachine: 'Independent Rig',
      description: 'A strong crawler drill machine for mining and deep hole drilling.',
      material: 'Reinforced Steel',
      weight: 12500,
      unit: 'pcs',
      manufacturer: 'PSR Drilling Systems',
      minStock: 2,
      maxStock: 10,
      currentStock: 3,
      status: 'AVAILABLE',
      images: ['/images/products/crawler_drill_rig.png'],
      barcode: 'BAR-PSR-C300',
      qrCode: 'QR-PSR-C300',
      costPrice: 85000.0,
      sellingPrice: 125000.0,
    },
    {
      name: 'PSR-W100 Pneumatic Wagon Drill',
      sku: 'PSR-W100-WAGON',
      code: 'PSR-W100',
      category: 'Drilling Rigs & Machinery',
      subCategory: 'Wagon Drills',
      compatibleMachine: 'Independent Rig',
      description: 'A versatile wheeled rig for quick shallow drilling in quarries.',
      material: 'Structural Steel',
      weight: 980,
      unit: 'pcs',
      manufacturer: 'PSR Drilling Systems',
      minStock: 3,
      maxStock: 15,
      currentStock: 5,
      status: 'AVAILABLE',
      images: ['/images/products/wagon_drill.png'],
      barcode: 'BAR-PSR-W100',
      qrCode: 'QR-PSR-W100',
      costPrice: 12000.0,
      sellingPrice: 18500.0,
    },
    {
      name: 'PSR-H6 Water Well Drilling Rig',
      sku: 'PSR-H6-WATERWELL',
      code: 'PSR-H6',
      category: 'Drilling Rigs & Machinery',
      subCategory: 'Water Well Rigs',
      compatibleMachine: 'Truck Mounted Rig',
      description: 'A heavy truck rig to drill deep water wells.',
      material: 'Structural Steel Frame',
      weight: 6200,
      unit: 'pcs',
      manufacturer: 'PSR Drilling Systems',
      minStock: 1,
      maxStock: 5,
      currentStock: 2,
      status: 'AVAILABLE',
      images: ['/images/products/inwell_drill.png'],
      barcode: 'BAR-PSR-H6',
      qrCode: 'QR-PSR-H6',
      costPrice: 95000.0,
      sellingPrice: 140000.0,
    },
    {
      name: 'Airtech Pneumatic Rock Drill',
      sku: 'AT-PNEUMATIC-ROCK-DRILL',
      code: 'AT-PRD-01',
      category: 'Drilling Rigs & Machinery',
      subCategory: 'Handheld Drills',
      compatibleMachine: 'Wagon Rigs',
      description: 'A strong cast iron rock drill for blast holes.',
      material: 'Heavy Cast Iron',
      weight: 24,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 5,
      maxStock: 30,
      currentStock: 12,
      status: 'AVAILABLE',
      images: ['/images/products/rock_drill.png'],
      barcode: 'BAR-AT-PRD-01',
      qrCode: 'QR-AT-PRD-01',
      costPrice: 1200.0,
      sellingPrice: 1950.0,
    },
    {
      name: 'Slim Drill LD4 Machine',
      sku: 'SLIM-DRILL-LD4',
      code: 'SD-LD4',
      category: 'Drilling Rigs & Machinery',
      subCategory: 'Core Drills',
      compatibleMachine: 'Confined Spaces',
      description: 'A small core drilling machine for narrow workspaces.',
      material: 'Lightweight Aluminum Alloy',
      weight: 180,
      unit: 'pcs',
      manufacturer: 'PSR Drilling Systems',
      minStock: 2,
      maxStock: 10,
      currentStock: 4,
      status: 'AVAILABLE',
      images: ['/images/products/slim_drill.png'],
      barcode: 'BAR-SD-LD4',
      qrCode: 'QR-SD-LD4',
      costPrice: 4500.0,
      sellingPrice: 6800.0,
    },
    {
      name: 'Airtech 70L4R Standard Pneumatic Motor',
      sku: 'AT-70L4R-STD',
      code: '70L4R-STD',
      category: 'Rotation Motors',
      subCategory: 'Pneumatic Motors',
      compatibleMachine: 'PSR-W100 wagon rig',
      description: 'Standard 4-piston radial pneumatic rotation drive.',
      material: 'Ductile Cast Iron',
      weight: 48.5,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 5,
      maxStock: 25,
      currentStock: 8,
      status: 'AVAILABLE',
      images: ['/images/products/pneumatic_motor.png'],
      barcode: 'BAR-70L4R-STD',
      qrCode: 'QR-70L4R-STD',
      costPrice: 3800.0,
      sellingPrice: 5200.0,
    },
    {
      name: 'Airtech 70L4R-T High-Torque Pneumatic Motor',
      sku: 'AT-70L4R-T',
      code: '70L4R-T',
      category: 'Rotation Motors',
      subCategory: 'Pneumatic Motors',
      compatibleMachine: 'PSR Crawler rigs',
      description: 'High-torque pneumatic motor with reinforced nose bearing cap.',
      material: 'High-alloy machined steel',
      weight: 52.0,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 3,
      maxStock: 20,
      currentStock: 6,
      status: 'AVAILABLE',
      images: ['/images/products/pneumatic_motor.png'],
      barcode: 'BAR-70L4R-T',
      qrCode: 'QR-70L4R-T',
      costPrice: 4500.0,
      sellingPrice: 6100.0,
    },
    {
      name: 'Airtech 70L4R-L Deep Borewell Pneumatic Motor',
      sku: 'AT-70L4R-L',
      code: '70L4R-L',
      category: 'Rotation Motors',
      subCategory: 'Pneumatic Motors',
      compatibleMachine: 'PSR Water Well rigs',
      description: 'Pneumatic motor with extended front drive spindle and double rubber mud seals.',
      material: 'Heat-treated 40Cr steel',
      weight: 56.5,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 2,
      maxStock: 15,
      currentStock: 4,
      status: 'AVAILABLE',
      images: ['/images/products/pneumatic_motor.png'],
      barcode: 'BAR-70L4R-L',
      qrCode: 'QR-70L4R-L',
      costPrice: 4900.0,
      sellingPrice: 6750.0,
    },

    // Inventory Parts (Spare Parts)
    {
      name: 'Airtech Pneumatic Rotation Motor (Full Assembly)',
      sku: 'PRM-AT-70L4R',
      code: 'AT-70L4R',
      category: 'Rotation Motors',
      subCategory: 'Pneumatic Motors',
      compatibleMachine: 'PSR-W100 Pneumatic Wagon Drill, PSR-C300 Crawler Drill',
      description: 'Complete heavy-duty 4-piston horizontal radial air rotation motor.',
      material: 'Ductile Cast Iron, High-Alloy Carbon Steel',
      weight: 48.5,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 5,
      maxStock: 50,
      currentStock: 8,
      status: 'AVAILABLE',
      images: ['/images/inventory/IMG_3116.jpg'],
      explodedView: '/images/inventory/IMG_3104.jpg',
      barcode: 'BAR-PRM-70L4R',
      qrCode: 'QR-PRM-AT-70L4R',
      costPrice: 4200.0,
      sellingPrice: 5950.0,
    },
    {
      name: 'Cast Iron Crankcase Housing',
      sku: 'AT-CCH-001',
      code: 'CCH-001',
      category: 'Crankcase',
      subCategory: 'Crankcase Casing',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Heavy cast-iron crankcase engine body block with four cylinder ports.',
      material: 'SG Ductile Iron Casting (Grade 500-7)',
      weight: 18.2,
      unit: 'pcs',
      manufacturer: "PSR'S Forging Division",
      minStock: 10,
      maxStock: 100,
      currentStock: 14,
      status: 'AVAILABLE',
      images: [
        '/images/inventory/crank case.jpg',
        '/images/inventory/crank case 1.jpg',
        '/images/inventory/crank case 2.jpg',
        '/images/inventory/crank case 3.jpg'
      ],
      barcode: 'BAR-CCH-001',
      qrCode: 'QR-AT-CCH-001',
      costPrice: 450.0,
      sellingPrice: 680.0,
    },
    {
      name: 'Reciprocating Piston Head',
      sku: 'AT-RPH-002',
      code: 'RPH-002',
      category: 'Piston Assembly',
      subCategory: 'Pistons',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'CNC-machined aluminum alloy piston head with dual compression grooves.',
      material: 'Anodized 6061-T6 Aluminum Alloy',
      weight: 0.45,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 20,
      maxStock: 200,
      currentStock: 48,
      status: 'AVAILABLE',
      images: [
        '/images/inventory/piston.jpg',
        '/images/inventory/piston 1.jpg',
        '/images/inventory/piston 2.jpg'
      ],
      technicalDrawing: '/images/inventory/piston ring.jpg',
      barcode: 'BAR-RPH-002',
      qrCode: 'QR-AT-RPH-002',
      costPrice: 85.0,
      sellingPrice: 135.0,
    },
    {
      name: 'Engine Connecting Rod',
      sku: 'AT-ECR-003',
      code: 'ECR-003',
      category: 'Piston Assembly',
      subCategory: 'Connecting Rods',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Forged steel connecting rod linking piston heads to the crankshaft web.',
      material: 'Forged 40CrNiMo Steel',
      weight: 0.85,
      unit: 'pcs',
      manufacturer: "PSR'S Forging Division",
      minStock: 10,
      maxStock: 100,
      currentStock: 32,
      status: 'AVAILABLE',
      images: ['/images/inventory/connecting rod.jpg'],
      barcode: 'BAR-ECR-003',
      qrCode: 'QR-AT-ECR-003',
      costPrice: 95.0,
      sellingPrice: 155.0,
    },
    {
      name: 'Rotary Air Distribution Valve',
      sku: 'AT-RADV-004',
      code: 'RADV-004',
      category: 'Valves',
      subCategory: 'Timing Valves',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Rotary timing valve core distributing pressurized air to radial cylinders.',
      material: 'Hardened Tool Steel (58-62 HRC)',
      weight: 1.65,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 5,
      maxStock: 50,
      currentStock: 18,
      status: 'AVAILABLE',
      images: ['/images/inventory/rotary valve.jpg', '/images/inventory/rotary valve 1.jpg'],
      barcode: 'BAR-RADV-004',
      qrCode: 'QR-AT-RADV-004',
      costPrice: 210.0,
      sellingPrice: 340.0,
    },
    {
      name: 'Cylinder Valve Head Cap',
      sku: 'AT-CVHC-005',
      code: 'CVHC-005',
      category: 'Valves',
      subCategory: 'Cylinder Heads',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Textured cast valve cylinder head with air supply thread connection ports.',
      material: 'Cast Bronze-Iron Alloy',
      weight: 1.25,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 5,
      maxStock: 60,
      currentStock: 22,
      status: 'AVAILABLE',
      images: ['/images/inventory/valve head.jpg', '/images/inventory/valve head 1.jpg'],
      barcode: 'BAR-CVHC-005',
      qrCode: 'QR-AT-CVHC-005',
      costPrice: 130.0,
      sellingPrice: 210.0,
    },
    {
      name: 'Deep Groove Ball Bearing 6210 2RS',
      sku: 'AT-BRG-6210',
      code: 'BRG-6210',
      category: 'Bearings & Seals',
      subCategory: 'Ball Bearings',
      compatibleMachine: 'Airtech 70L4R Motor, PSR-W100 rig spindle',
      description: 'Double rubber-sealed bearing for main drive shaft spindle shafts.',
      material: 'High-Chromium Steel (GCr15)',
      weight: 0.46,
      unit: 'pcs',
      manufacturer: 'NSK Industrial',
      minStock: 20,
      maxStock: 200,
      currentStock: 65,
      status: 'AVAILABLE',
      images: ['/images/inventory/Bearing-6210 2rs.jpg', '/images/inventory/Bearing-6210 2rs 1.jpg'],
      barcode: 'BAR-BRG-6210',
      qrCode: 'QR-AT-BRG-6210',
      costPrice: 30.0,
      sellingPrice: 52.0,
    },
    {
      name: 'Deep Groove Ball Bearing 6208 2RS',
      sku: 'AT-BRG-6208',
      code: 'BRG-6208',
      category: 'Bearings & Seals',
      subCategory: 'Ball Bearings',
      compatibleMachine: 'Airtech 70L4R Motor, PSR-W100 frame pivot',
      description: 'Double rubber-sealed ball bearing supporting the crankshaft rear end.',
      material: 'High-Chromium Steel (GCr15)',
      weight: 0.37,
      unit: 'pcs',
      manufacturer: 'NSK Industrial',
      minStock: 20,
      maxStock: 250,
      currentStock: 80,
      status: 'AVAILABLE',
      images: ['/images/inventory/Bearing-6208 2rs.jpg'],
      barcode: 'BAR-BRG-6208',
      qrCode: 'QR-AT-BRG-6208',
      costPrice: 22.0,
      sellingPrice: 38.0,
    },
    {
      name: 'Crankshaft Counterbalance Weight',
      sku: 'AT-CCW-006',
      code: 'CCW-006',
      category: 'Crankcase',
      subCategory: 'Balancers',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Forged crankshaft balance web featuring dynamic air breathing holes.',
      material: 'Forged High-Nickel Carbon Steel',
      weight: 2.40,
      unit: 'pcs',
      manufacturer: "PSR'S Forging Division",
      minStock: 5,
      maxStock: 50,
      currentStock: 15,
      status: 'AVAILABLE',
      images: [
        '/images/inventory/balance with filter.jpg',
        '/images/inventory/balance with filter 1.jpg',
        '/images/inventory/balance with filter 2.jpg',
        '/images/inventory/balance with filter 3.jpg',
        '/images/inventory/balance without filter.jpg',
        '/images/inventory/balance without filter 1.jpg'
      ],
      barcode: 'BAR-CCW-006',
      qrCode: 'QR-AT-CCW-006',
      costPrice: 110.0,
      sellingPrice: 180.0,
    },
    {
      name: 'Crankshaft Bushing Sleeve',
      sku: 'AT-CBS-007',
      code: 'CBS-007',
      category: 'Bearings & Seals',
      subCategory: 'Bushings',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Wear-resistant phosphor bronze bushing sleeve for crankshaft journals.',
      material: 'Phosphor Bronze Alloy (CuSn8)',
      weight: 0.12,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 10,
      maxStock: 100,
      currentStock: 40,
      status: 'AVAILABLE',
      images: ['/images/inventory/crank bush.jpg', '/images/inventory/crank bush 1.jpg'],
      barcode: 'BAR-CBS-007',
      qrCode: 'QR-AT-CBS-007',
      costPrice: 18.0,
      sellingPrice: 32.0,
    },
    {
      name: 'Piston Pin Circlip (Retaining Ring)',
      sku: 'AT-PPC-008',
      code: 'PPC-008',
      category: 'Bearings & Seals',
      subCategory: 'Retaining Rings',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Spring-steel snap circlip securing gudgeon pins in piston bores.',
      material: 'Carbon Spring Steel (C75S)',
      weight: 0.005,
      unit: 'pcs',
      manufacturer: 'FastenTech Corp.',
      minStock: 50,
      maxStock: 1000,
      currentStock: 250,
      status: 'AVAILABLE',
      images: ['/images/inventory/circling.jpg'],
      barcode: 'BAR-PPC-008',
      qrCode: 'QR-AT-PPC-008',
      costPrice: 1.5,
      sellingPrice: 3.5,
    },
    {
      name: 'M10 Hex Cap Bolt (30mm)',
      sku: 'AT-FAS-M10-30',
      code: 'FAS-M10-30',
      category: 'Fasteners',
      subCategory: 'Bolts',
      compatibleMachine: 'Airtech 70L4R Motor, universal heavy drill rigs',
      description: 'Grade 8.8 high-tensile zinc plated M10 hex bolts for structural covers.',
      material: 'Carbon Steel (Grade 8.8, Zinc Plated)',
      weight: 0.024,
      unit: 'pcs',
      manufacturer: 'FastenTech Corp.',
      minStock: 100,
      maxStock: 2000,
      currentStock: 500,
      status: 'AVAILABLE',
      images: [
        '/images/inventory/BOlt - m10  l30.jpg',
        '/images/inventory/bolt - m10 , l 30.jpg',
        '/images/inventory/bolt m10 , l30 1.jpg'
      ],
      barcode: 'BAR-FAS-M10-30',
      qrCode: 'QR-AT-FAS-M10-30',
      costPrice: 0.8,
      sellingPrice: 1.9,
    },
    {
      name: 'Rubber O-Ring Seal',
      sku: 'AT-ORS-009',
      code: 'ORS-009',
      category: 'Bearings & Seals',
      subCategory: 'O-Rings',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'NBR Nitrile rubber static seal O-ring preventing crankcase grease loss.',
      material: 'NBR Nitrile Rubber (70 Shore A)',
      weight: 0.008,
      unit: 'pcs',
      manufacturer: 'SealKing Ind.',
      minStock: 30,
      maxStock: 500,
      currentStock: 180,
      status: 'AVAILABLE',
      images: ['/images/inventory/o ring.jpg'],
      barcode: 'BAR-ORS-009',
      qrCode: 'QR-AT-ORS-009',
      costPrice: 2.2,
      sellingPrice: 4.8,
    },
    {
      name: 'Valve Head Gasket (Packing)',
      sku: 'AT-VHP-010',
      code: 'VHP-010',
      category: 'Bearings & Seals',
      subCategory: 'Gaskets',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'High-pressure cylinder cap compound packing seal gasket.',
      material: 'Graphite-Metal Composite Laminate',
      weight: 0.015,
      unit: 'pcs',
      manufacturer: 'SealKing Ind.',
      minStock: 20,
      maxStock: 300,
      currentStock: 90,
      status: 'AVAILABLE',
      images: ['/images/inventory/valve head packing.jpg'],
      barcode: 'BAR-VHP-010',
      qrCode: 'QR-AT-VHP-010',
      costPrice: 5.5,
      sellingPrice: 11.5,
    },
    {
      name: 'Crankcase Top Cover Plate',
      sku: 'AT-TCP-011',
      code: 'TCP-011',
      category: 'Crankcase',
      subCategory: 'Covers',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Cast iron cover plate securing the crankcase inspection port.',
      material: 'Cast Iron Alloy',
      weight: 1.45,
      unit: 'pcs',
      manufacturer: "PSR'S Forging Division",
      minStock: 3,
      maxStock: 30,
      currentStock: 12,
      status: 'AVAILABLE',
      images: ['/images/inventory/top cover.jpg', '/images/inventory/top cover 1.jpg'],
      barcode: 'BAR-TCP-011',
      qrCode: 'QR-AT-TCP-011',
      costPrice: 45.0,
      sellingPrice: 75.0,
    },
    {
      name: 'Crosshead Guide Slide Block',
      sku: 'AT-CGSB-012',
      code: 'CGSB-012',
      category: 'Crankcase',
      subCategory: 'Guide Blocks',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Friction slider block directing reciprocating piston pin travel.',
      material: 'Sintered Copper-Steel Matrix',
      weight: 0.34,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 5,
      maxStock: 100,
      currentStock: 25,
      status: 'AVAILABLE',
      images: ['/images/inventory/linear block.jpg'],
      barcode: 'BAR-CGSB-012',
      qrCode: 'QR-AT-CGSB-012',
      costPrice: 38.0,
      sellingPrice: 62.0,
    },
    {
      name: 'Pneumatic Air Filter Element',
      sku: 'AT-PAFE-013',
      code: 'PAFE-013',
      category: 'Air System',
      subCategory: 'Filters',
      compatibleMachine: 'Airtech 70L4R Motor, universal pneumatic lines',
      description: 'Sintered bronze air filter core removing moisture and line dust.',
      material: 'Sinter sintered Bronze Powder',
      weight: 0.18,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 10,
      maxStock: 150,
      currentStock: 42,
      status: 'AVAILABLE',
      images: ['/images/inventory/Air tech filter.jpg', '/images/inventory/Air tech filter 1.jpg'],
      barcode: 'BAR-PAFE-013',
      qrCode: 'QR-AT-PAFE-013',
      costPrice: 28.0,
      sellingPrice: 48.0,
    },
    {
      name: 'Pneumatic Motor Forged Crankshaft',
      sku: 'AT-MFC-014',
      code: 'MFC-014',
      category: 'Crankcase',
      subCategory: 'Crankshafts',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Forged crankshaft featuring single throw offset pin and counterweight seat.',
      material: 'Forged Chrome-Moly Alloy Steel (42CrMo4)',
      weight: 5.20,
      unit: 'pcs',
      manufacturer: "PSR'S Forging Division",
      minStock: 3,
      maxStock: 20,
      currentStock: 6,
      status: 'LOW_STOCK',
      images: ['/images/inventory/IMG_3086.jpg', '/images/inventory/IMG_3087.jpg'],
      barcode: 'BAR-MFC-014',
      qrCode: 'QR-AT-MFC-014',
      costPrice: 240.0,
      sellingPrice: 390.0,
    },
    {
      name: 'Cylinder Sleeve Liner Barrel',
      sku: 'AT-CSLB-015',
      code: 'CSLB-015',
      category: 'Piston Assembly',
      subCategory: 'Cylinder Liners',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Precision honed cylinder sleeve sleeve barrel liner.',
      material: 'High-Phosphorus Centrifugally Cast Iron',
      weight: 2.10,
      unit: 'pcs',
      manufacturer: "PSR'S Forging Division",
      minStock: 5,
      maxStock: 50,
      currentStock: 12,
      status: 'AVAILABLE',
      images: ['/images/inventory/IMG_3089.jpg'],
      barcode: 'BAR-CSLB-015',
      qrCode: 'QR-AT-CSLB-015',
      costPrice: 75.0,
      sellingPrice: 125.0,
    },
    {
      name: 'Output Drive Shaft Assembly',
      sku: 'AT-ODSA-016',
      code: 'ODSA-016',
      category: 'Crankcase',
      subCategory: 'Drive Shafts',
      compatibleMachine: 'Airtech 70L4R Motor, Wagon Drill rotations',
      description: 'Front drive shaft with machined keyway and API threaded tip.',
      material: 'Structural Alloy Steel (40Cr)',
      weight: 3.60,
      unit: 'pcs',
      manufacturer: "PSR'S Forging Division",
      minStock: 3,
      maxStock: 40,
      currentStock: 10,
      status: 'AVAILABLE',
      images: ['/images/inventory/IMG_3093.jpg', '/images/inventory/IMG_3095.jpg'],
      barcode: 'BAR-ODSA-016',
      qrCode: 'QR-AT-ODSA-016',
      costPrice: 180.0,
      sellingPrice: 290.0,
    },
    {
      name: 'Rotary Valve Chest Housing',
      sku: 'AT-RVCH-017',
      code: 'RVCH-017',
      category: 'Valves',
      subCategory: 'Valve Housings',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Cast valve chest housing enclosing the rotary timing timing valve.',
      material: 'Cast Grey Iron (GG25)',
      weight: 3.10,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 3,
      maxStock: 40,
      currentStock: 15,
      status: 'AVAILABLE',
      images: ['/images/inventory/IMG_3097.jpg', '/images/inventory/IMG_3099.jpg'],
      barcode: 'BAR-RVCH-017',
      qrCode: 'QR-AT-RVCH-017',
      costPrice: 95.0,
      sellingPrice: 165.0,
    },
    {
      name: 'Spacer Thrust Washer Set',
      sku: 'AT-STWS-018',
      code: 'STWS-018',
      category: 'Bearings & Seals',
      subCategory: 'Washers',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Hardened steel thrust washers adjusting crankshaft end-play clearances.',
      material: 'Hardened Spring Steel (65Mn)',
      weight: 0.015,
      unit: 'pcs',
      manufacturer: 'FastenTech Corp.',
      minStock: 20,
      maxStock: 500,
      currentStock: 120,
      status: 'AVAILABLE',
      images: ['/images/inventory/IMG_3103.jpg'],
      barcode: 'BAR-STWS-018',
      qrCode: 'QR-AT-STWS-018',
      costPrice: 4.5,
      sellingPrice: 9.5,
    },
    {
      name: 'Drive Shaft Feather Key',
      sku: 'AT-DSFK-019',
      code: 'DSFK-019',
      category: 'Fasteners',
      subCategory: 'Keys',
      compatibleMachine: 'Airtech 70L4R Motor, universal keyways',
      description: 'Precision ground rectangular drive key for coupling shafts.',
      material: 'Medium Carbon Steel (C45)',
      weight: 0.012,
      unit: 'pcs',
      manufacturer: 'FastenTech Corp.',
      minStock: 50,
      maxStock: 1000,
      currentStock: 300,
      status: 'AVAILABLE',
      images: ['/images/inventory/IMG_3105.jpg'],
      barcode: 'BAR-DSFK-019',
      qrCode: 'QR-AT-DSFK-019',
      costPrice: 1.2,
      sellingPrice: 2.8,
    },
    {
      name: 'Exhaust Port Deflector Cap',
      sku: 'AT-EPDC-020',
      code: 'EPDC-020',
      category: 'Air System',
      subCategory: 'Silencers',
      compatibleMachine: 'Airtech 70L4R Motor',
      description: 'Deflector cap directing exhaust air discharge and silencing sound.',
      material: 'Weather-resistant ABS Polymer',
      weight: 0.08,
      unit: 'pcs',
      manufacturer: 'Airtech Pneumatics Ltd.',
      minStock: 5,
      maxStock: 100,
      currentStock: 45,
      status: 'AVAILABLE',
      images: ['/images/inventory/IMG_3106.jpg'],
      barcode: 'BAR-EPDC-020',
      qrCode: 'QR-AT-EPDC-020',
      costPrice: 12.0,
      sellingPrice: 24.0,
    },
  ];

  // 4. Seeding Products
  let index = 0;
  for (const prod of productsToSeed) {
    const categoryId = categoryMap[prod.category];
    if (!categoryId) {
      console.warn(`Category "${prod.category}" not found for product "${prod.name}". Skipping.`);
      continue;
    }

    const { category, ...productData } = prod;

    const createdProduct = await prisma.product.upsert({
      where: { sku: prod.sku },
      update: {
        currentStock: prod.currentStock,
        status: prod.status as any,
        costPrice: prod.costPrice,
        sellingPrice: prod.sellingPrice,
        subCategory: prod.subCategory,
        images: prod.images,
        description: prod.description,
        compatibleMachine: prod.compatibleMachine,
        material: prod.material,
        weight: prod.weight,
        barcode: prod.barcode,
        qrCode: prod.qrCode,
      },
      create: {
        ...productData,
        status: prod.status as any,
        categoryId,
      },
    });

    console.log(`Product upserted: ${createdProduct.name} (SKU: ${createdProduct.sku})`);

    index++;
  }

  // 5. Seed ProductLocations for ALL warehouses, racks, shelves, and positions evenly
  console.log('Seeding ProductLocations evenly across all positions...');
  
  const warehouseNames = ['Main Warehouse A', 'Small Parts Sump B', 'Bearing Drawer C', 'Logistics Locker D'];
  const rackNames = ['Rack A', 'Rack B', 'Rack C', 'Rack D', 'Rack P', 'Rack S'];
  const shelfNames = ['Shelf 1', 'Shelf 2', 'Shelf 3', 'Shelf 4', 'Shelf 5'];
  const positionNames = ['Pos 1', 'Pos 2', 'Pos 3', 'Pos 4'];
  
  const dbProducts = await prisma.product.findMany();
  let locationIndex = 0;
  
  await prisma.productLocation.deleteMany({});
  
  for (const whName of warehouseNames) {
    const warehouseId = warehouseMap[whName];
    if (!warehouseId) continue;
    
    for (const rackName of rackNames) {
      const rack = await prisma.rack.upsert({
        where: { id: `rack-${rackName}-${warehouseId}` },
        create: {
          id: `rack-${rackName}-${warehouseId}`,
          name: rackName,
          warehouseId,
        },
        update: {},
      });
      
      for (const posName of positionNames) {
        const position = await prisma.position.upsert({
          where: { id: `pos-${posName}-${rack.id}` },
          create: {
            id: `pos-${posName}-${rack.id}`,
            name: posName,
            rackId: rack.id,
          },
          update: {},
        });
        
        for (const shelfName of shelfNames) {
          const product = dbProducts[locationIndex % dbProducts.length];
          // Generates a nice even mix of optimal (15-80), critical (81-99), and empty (0)
          const qtyRaw = (locationIndex * 31) % 100;
          const quantity = qtyRaw < 15 ? 0 : qtyRaw;
          
          if (quantity > 0) {
            await prisma.productLocation.create({
              data: {
                productId: product.id,
                warehouseId,
                rackId: rack.id,
                positionId: position.id,
                shelfNumber: shelfName,
                quantity,
              }
            });
          }
          
          locationIndex++;
        }
      }
    }
  }

  // 6. Update Product currentStock levels to match the sum of their physical locations
  console.log('Syncing product stock levels...');
  const allProducts = await prisma.product.findMany();
  for (const prod of allProducts) {
    const locs = await prisma.productLocation.findMany({
      where: { productId: prod.id }
    });
    const totalStock = locs.reduce((sum, l) => sum + l.quantity, 0);
    
    let newStatus = 'AVAILABLE';
    if (totalStock === 0) {
      newStatus = 'OUT_OF_STOCK';
    } else if (totalStock < prod.minStock) {
      newStatus = 'LOW_STOCK';
    }
    
    await prisma.product.update({
      where: { id: prod.id },
      data: {
        currentStock: totalStock,
        status: newStatus as any,
      }
    });
  }

  console.log('Seeding completed successfully.');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
  });
